### ISSUE TITLE
UMBRELLA - Refactor List

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#86]
_Also mentioned in https://github.com/UXARRAY/uxarray/discussions/88#discussioncomment-3335677_

The code base seems to need some refactoring, which can be listed below:

- [ ] Avoid using "Double Leading and Trailing Underscore" with the function and attribute names as they are reserved for Python language's special usage (e.g. `__init__` is ok, but `def __from_ds__` should better be renamed)
- [ ] Comment/docstring to function name/task inconsistencies (e.g. `def __from_ds__(self, dataset)`) as well as comment/docstrings cleanup (the same function has both a comment and a docstring in almost same phrases)
- [ ] Avoid wildcard imports as much as possible as they make it hard to know what actual code is being used from those imports (e.g. `from .helpers import *`)
